### ISSUE TITLE
Decide on an official register for plugins

### ISSUE THREAD

**Issue by cwognum** [datamol-io/molfeat#10]
The [current version](https://datamol-io.github.io/molfeat/stable/developers/register-plugin.html) of the documentation still has a page on registering plugins. We had some internal discussions on whether we want to keep this and - if so - if this is the best way of doing so. Due to practically unlimited flexibility of the plugin system, there are some challenges. Creating this issue to track that discussion and to make sure we make a decision before the release. 

ping @maclandrol

**Comment by cwognum** [comment]
@maclandrol This can be closed now, right?

**Comment by maclandrol** [comment]
Yes, I think it's covered.  I added issue template. Would be nice to have a PR template for plugin, but I am fine with the current workflow.
