### ISSUE TITLE
transformer not found ChemBERTa-77M-MLM

### ISSUE THREAD

**Issue by davidesala** [datamol-io/molfeat#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing

### Bug description

running this 
trans_chemberta = PretrainedHFTransformer(kind='ChemBERTa-77M-MLM', notation='smiles')
I get this
ValueError: Cannot find transformers and/or tokenizers. It's required for this featurizer !
suggestions?

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Molfeat version (e.g., 0.1.0):
#- PyTorch Version (e.g., 1.10.0):
#- RDKit version (e.g., 2022.09.5): 
#- scikit-learn version (e.g.,  1.2.1): 
#- OS (e.g., Linux):
#- How you installed Molfeat (`conda`, `pip`, source):
```

</details>

**Comment by zhu0619** [comment]
Hi @davidesala, 
Thank you for using Molfeat. 
To resolve the error, please ensure that the `transformers`package is installed.
You can follow this[ installation instruction](https://huggingface.co/docs/transformers/en/installation). 

Please let me know if the issue persists after this step.

**Comment by davidesala** [comment]
uh, thanks
