### ISSUE TITLE
Add DOI

### ISSUE THREAD

**Issue by cwognum** [datamol-io/molfeat#14]
Add a DOI to cite, as was done for Datamol: https://zenodo.org/record/7768542#.ZB8SlXXMKV5
Then we can update the badge in the README and docs. 

ping @hadim : Is this something I can do? Or do we have a central account to use? Any CICD to setup?

**Comment by hadim** [comment]
Nothing to do in that repo directly and it's fairly easy and fast from what I recall. You can give it a try (I will bump your permissions on that repo).

Documentation: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by hadim** [comment]
(I put you as admin of the molfeat repo)

**Comment by cwognum** [comment]
Should be setup! It indeed was easy to do. We just need to release a new version to get the DOI.

**Comment by hadim** [comment]
you can release any time by running locally `rever 0.8.1`, once done that ci is going to be triggered: https://github.com/datamol-io/molfeat/actions/workflows/release.yml

**Comment by cwognum** [comment]
I'll do so once some more of the changes have been merged! Otherwise it's such a useless version! :wink:

**Comment by cwognum** [comment]
[![DOI](https://zenodo.org/badge/613548667.svg)](https://zenodo.org/badge/latestdoi/613548667)

:tada: 

Still need to update it in the docs! Will do that after lunch!
