### ISSUE TITLE
Move docs to `molfeat-docs.datamol.io`

### ISSUE THREAD

**Issue by cwognum** [datamol-io/molfeat#16]
### 📖 Documentation

Docs are currently hosted on https://datamol-io.github.io/molfeat/stable/index.html
This should be [docs.molfeat.datamol.io](docs.molfeat.datamol.io).

**Comment by maclandrol** [comment]
I think subsub domain are a bit weirds. [molfeat-docs.datamol.io](http://molfeat-docs.datamol.io/) might be better
