### ISSUE TITLE
GPT models give error using the example code

### ISSUE THREAD

**Issue by cbirchsy** [datamol-io/molfeat#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing

### Bug description

GPT based models (e.g [ChemGPT-4.7M](https://molfeat.datamol.io/featurizers/ChemGPT-4.7M) and [ChemGPT-1.2B](https://molfeat.datamol.io/featurizers/ChemGPT-1.2B)) do not work out-of-the-box using the example code from the [featurizer hub](https://molfeat.datamol.io/featurizers). 

### How to reproduce the bug

```python
import datamol as dm
from molfeat.trans.pretrained.hf_transformers import PretrainedHFTransformer

data = dm.freesolv().iloc[:100]
transformer = PretrainedHFTransformer(kind="ChemGPT-4.7M", notation="selfies")
features = transformer(data["smiles"])
```

### Error messages and logs

```
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
```

### Environment

<details>
  <summary>Current environment</summary>

```
 - Transformers version: 4.27.4
 - Molfeat version: 0.8.5
```

</details>

**Comment by maclandrol** [comment]
Thanks @cbirchsy, I will have a look. The ChemGPT models were not properly saved by the authors and required patching. It seems like we might have mixed a special token.

**Comment by cbirchsy** [comment]
I see, thanks!

**Comment by maclandrol** [comment]
@cbirchsy, 

I have patched the files, let me know if it's working. 

You will need to run the following lines to clear your local cache. If you are not using the default cache, please adjust:

```python
import datamol as dm
import platformdirs

# remove chemgpt local dir
try:
    chemgpt_local_dir = dm.fs.join(platformdirs.user_cache_dir("molfeat"), "ChemGPT-4.7M")
    mapper = dm.fs.get_mapper(chemgpt_local_dir)
    mapper.fs.delete(chemgpt_local_dir, recursive=True)
except FileNotFoundError:
    pass

# make sure we clear the cache of the HFModel function
from molfeat.trans.pretrained.hf_transformers import HFModel
HFModel._load_or_raise.cache_clear()
```

Now let's test again:

```python
import datamol as dm
import os
from molfeat.trans.pretrained.hf_transformers import PretrainedHFTransformer

os.environ["TOKENIZERS_PARALLELISM"] = "false" # annoying huggingface warning
data = dm.freesolv().iloc[:100]
transformer = PretrainedHFTransformer(kind="ChemGPT-4.7M", notation="selfies")
features = transformer(data["smiles"])
```

Feel free to close the issue if this has solved it.

**Comment by cbirchsy** [comment]
Awesome, working for me now. Thanks!
