### ISSUE TITLE
Import path for FPVecTransformer incorrect for current version in documentation example. 

### ISSUE THREAD

**Issue by jparkhill** [datamol-io/molfeat#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing

### Bug description

<img width="684" alt="image" src="https://user-images.githubusercontent.com/4132346/231817817-69bf367e-a556-4147-964c-ecc8374b0825.png">

it's missing the ".fp" submodule? 

<img width="684" alt="image" src="https://user-images.githubusercontent.com/4132346/231817944-ea01572e-ccd3-4f7f-99d3-eb10dab99170.png">

Installed fresh via pip3. Python 3.9. 

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Molfeat version (e.g., 0.1.0):
#- PyTorch Version (e.g., 1.10.0):
#- RDKit version (e.g., 2022.09.5): 
#- scikit-learn version (e.g.,  1.2.1): 
#- OS (e.g., Linux):
#- How you installed Molfeat (`conda`, `pip`, source):
```

</details>

**Comment by maclandrol** [comment]
Nice catch, thanks @jparkhill.
