### ISSUE TITLE
Design / Concept doc as a separate page.

### ISSUE THREAD

**Issue by maclandrol** [datamol-io/molfeat#71]
I found the FAQ to be excellent.

Given how much information is given in the FAQ, maybe it would be worth having a dedicated section (or more than one) on the usage.md page or another one covering the basics design concepts of `molfeat`? Those would be based on the various questions in the FAQ (and probably make the FAQ shorter).

It's just a proposal since I found the FAQ to already be super informative without more changes.

_Originally posted by @hadim in https://github.com/datamol-io/molfeat/pull/70#pullrequestreview-1545251164_

**Comment by cwognum** [comment]
I really like the FAQ too! 

Another idea could be to use [collapsible admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks) to make the information easier to parse. There already is a `question` type admonition, but we could also customize this or add our own if we dislike the colors / icon.
