### ISSUE TITLE
Clarify Installation Requirements to run tests locally

### ISSUE THREAD

**Issue by JacksonBurns** [datamol-io/molfeat#72]
### 📖 Documentation

To run the tests locally, I had to do a 'full' install, i.e. `pip install -e .[full]` from my cloned repo and manually install `pytest`. If this procedure could either be clarified in the contributors document, or a more minimal `dev` extras section (that includes `pytest`) could be added to the `pyproject.toml`, that would be helpful.

**Comment by maclandrol** [comment]
@JacksonBurns  would you like to add that to your current PR ?

**Comment by JacksonBurns** [comment]
I'm not sure, is that the intended solution? If some of the dependencies are not required for testing it would be nice to have a minimal dev package, but I don't know enough about `molfeat` to say.

**Comment by maclandrol** [comment]
We use conda mainly to manage our environment and dependencies. I will clarify that, but adding alternative through pip is also a good idea.

**Comment by maclandrol** [comment]
https://github.com/datamol-io/molfeat/pull/75 should address this issue.
