### ISSUE TITLE
GPT2-Zinc480M-87M and Roberta-Zinc480M-102M not retrievable

### ISSUE THREAD

**Issue by arunraja-hub** [datamol-io/molfeat#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing

### Bug description

I have been trying to use GPT2-Zinc480M-87M and Roberta-Zinc480M-102M and I am getting the following error.
The code is as https://molfeat.datamol.io/featurizers/GPT2-Zinc480M-87M
The error message:
```
 molfeat.store.modelstore.ModelStoreError: Can't retrieve model GPT2-Zinc480M-87M from the store !
```

### How to reproduce the bug

```python
https://molfeat.datamol.io/featurizers/GPT2-Zinc480M-87M
```

### Error messages and logs

```
 molfeat.store.modelstore.ModelStoreError: Can't retrieve model GPT2-Zinc480M-87M from the store !
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Molfeat version (e.g., 0.1.0):
#- PyTorch Version (e.g., 1.10.0):
#- RDKit version (e.g., 2022.09.5): 
#- scikit-learn version (e.g.,  1.2.1): 
#- OS (e.g., Linux):
#- How you installed Molfeat (`conda`, `pip`, source):
```

</details>

**Comment by maclandrol** [comment]
Hello @arunraja-hub , I have attempted several time to reproduce this bug without success.

Let me know if which steps you took.

**Comment by dyan-yen** [comment]
Hi, I had the same issue earlier today too. In my case, if I downgrade the package `fsspec` v2023.9.2 to v2023.6.0, the error would be gone and everything works for me again. 

(I am using molfeat v0.9.4)

**Comment by maclandrol** [comment]
Thanks @dyan-yen, I think it might be a bug recently introduced in fsspec. I believe they don't  `auto-create` folder on file opening on write mode anymore. Should be easy to fix.
