### ISSUE TITLE
Update the collate_fn for PYGGraphTransformer

### ISSUE THREAD

**Issue by zhu0619** [datamol-io/molfeat#92]
### Motivation

For the latest version of torch_geometric 2.4.0, the [Collater](https://github.com/pyg-team/pytorch_geometric/blob/bf0419b9c4c89cf2e5b90f53cceb5a8286e58679/torch_geometric/loader/dataloader.py#L14) was refactored and require an argument `dataset`. 

Therefore, the current implementation of [`PYGGraphTransformer.get_collate_fn`](https://github.com/datamol-io/molfeat/blob/8272a6f67d99d8ad1fed078ca067cef3836c3d53/molfeat/trans/graph/adj.py#L746C26-L746C26) is no longer  valid. 

### Pitch

The argument `dataset` should also be added in the `get_collate_fn`. 

```
def get_collate_fn(
        self,
        dataset: Union[Dataset, Sequence[BaseData], DatasetAdapter],
        follow_batch: Optional[List[str]] = None,
        exclude_keys: Optional[List[str]] = None,
        return_pair: Optional[bool] = True,
        **kwargs,
    ):
        collator = Collater(dataset=dataset, follow_batch=follow_batch, exclude_keys=exclude_keys)
        return partial(self._collate_batch, collator=collator, return_pair=return_pair)
```

**Comment by maclandrol** [comment]
Thanks @zhu0619, can you make a PR ?

**Comment by maclandrol** [comment]
@zhu0619, can you document the alternative of using the pyg [DataLoader](https://github.com/pyg-team/pytorch_geometric/blob/bf0419b9c4c89cf2e5b90f53cceb5a8286e58679/torch_geometric/loader/dataloader.py#L58) object directly somewhere ?

It allows actually not providing any collate function
