### ISSUE TITLE
DEPRECATION WARNING: please use MorganGenerator

### ISSUE THREAD

**Issue by isty2e** [datamol-io/molfeat#98]
### Motivation

`DeprecationWarning` appears generating fingerprints (e.g., ECFP) with `FPVecTransformer` when a recent version of RDKit is installed. Like in `datamol`, the code can be reworked to use `rdFingerprintGenerator`.

### Pitch

The `DeprecationWarning` is the main issue for me, and in fact the implementation does not matter as long as it can be suppressed.

### Additional context

Related issue: https://github.com/datamol-io/datamol/issues/225

**Comment by maclandrol** [comment]
Hi @isty2e  would you be able to make a PR here to fix the issue ?

**Comment by isty2e** [comment]
@maclandrol Made the PR.
